
GET http://localhost:3000/posts

###
POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "My second Post",
  "content": "This is the content of my first post."
}

###
GET http://localhost:3000/posts/1

###
PUT http://localhost:3000/posts/2
Content-Type: application/json

{
  "title": "Updated  Title",
  "content": "This is the updated content of my post."
}

###
DELETE http://localhost:3000/posts/3
